name: Checking Tests Repository

on: [ pull_request, push ]

jobs:

  build:
    runs-on: ubuntu-latest

    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with: 
            fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v1
        with: 
            node-version: 16

      - name: Install Dependencies
        run: yarn